### PR TITLE
Adding Roomba, RoombaEst, FullState, and BayesianUpdate messages.

### PR DESCRIPTION
**Pull request by suryabhupa**
These have been ported from the old messages repo on BitBucket and constitute some subset of CV's messages.

### CODE REVIEW

**Comment by rohanb2018** [comment]
Looks all right to me.

**Comment by suryabhupa** [comment]
Where are we keeping track of Roomba velocities, or at least the angle at which it's traveling? Should this be added to RoombaLocation?

**Comment by squilter** [comment]
I think we should make it more obvious that these are only what the camera sees, and they do not tell us where these roombas are on the field (until we compare it with the EKF's position estimate of the vehicle location).

Regarding line segments, I thought we decided to switch to the grid by the intersections, not the x1,x2,y1,y2 of the line.

Also, the color of the roomba is missing.  We don't need it yet, but we should have it in our message spec.

**Comment by squilter** [comment]
RoombaLocation has an X and Y that are defined as
`# Position in UAV-centered body frame`

Not exactly clear what this means.  Is this the distance along the ground to a roomba?  Meters, centimeters, ...?

Also, CV doesn't know the altitude of our copter, so it can't know this info.  All CV will know is what pixel the object is at.

**Comment by squilter** [comment]
Every time there is a new frame from the camera, CV will publish the grid intersections and the roombas.  As currently defined, they are in two separate messages and we could potentially lose synchronization and end up comparing grid intersections from time t=34.12 to roombas from t=34.15 or something.

What if we created a message called CVFeature.  CVfeature stores an x and y (in pixels offset from center), and it stores a "type".  Then one big message stores a list of CVfeatures.  Then, every time there is a new frame, CV would publish one big message with the following info:

[
[405,231,red_roomba]
[-234,-654,green_roomba]
[256,321,grid_intersect]
[132,465,grid_intersect]
[766,561,grid_intersect]
...
]

**Comment by suryabhupa** [comment]
I do like this new approach; all these numbers are relative to the center of what the UAV sees, right?

**Comment by squilter** [comment]
Yes.  Anything directly under the UAV would be 0,0.

**Comment by suryabhupa** [comment]
Cool. Should I close this and you can make the 100 -> 3 change in #7?

**Comment by squilter** [comment]
I made the change to mine.  I also added a comment to say that it is measured in pixels.  Since there have been no other comments in almost a week, I think it is appropriate to move on by closing this one.

**Comment by suryabhupa** [comment]
Sounds good.

**Comment by suryabhupa** [comment]
Is the CV team going to be providing thetas for directions of the Roombas it sees?

**Comment by suryabhupa** [comment]
More messages to be added to the Messages folder.

**Pull request merged**
